import { Piece, PieceType, Player } from '@/types/app.types';

export const initialPosition: Array<Piece> = [
  {
    id: 1,
    player: Player.black,
    type: PieceType.rook,
    position: 0,
    moved: false,
    moves: [8, 16, 17],
  },
  {
    id: 2,
    player: Player.black,
    type: PieceType.knight,
    position: 1,
    moved: false,
    moves: [],
  },
  {
    id: 3,
    player: Player.black,
    type: PieceType.bishop,
    position: 2,
    moved: false,
    moves: [],
  },
  {
    id: 4,
    player: Player.black,
    type: PieceType.queen,
    position: 3,
    moved: false,
    moves: [],
  },
  {
    id: 5,
    player: Player.black,
    type: PieceType.king,
    position: 4,
    moved: false,
    moves: [],
  },
  {
    id: 6,
    player: Player.black,
    type: PieceType.bishop,
    position: 5,
    moved: false,
    moves: [],
  },
  {
    id: 7,
    player: Player.black,
    type: PieceType.knight,
    position: 6,
    moved: false,
    moves: [],
  },
  {
    id: 8,
    player: Player.black,
    type: PieceType.rook,
    position: 7,
    moved: false,
    moves: [],
  },
  {
    id: 9,
    player: Player.black,
    type: PieceType.pawn,
    position: 8,
    moved: false,
    moves: [],
  },
  {
    id: 10,
    player: Player.black,
    type: PieceType.pawn,
    position: 9,
    moved: false,
    moves: [],
  },
  {
    id: 11,
    player: Player.black,
    type: PieceType.pawn,
    position: 10,
    moved: false,
    moves: [],
  },
  {
    id: 12,
    player: Player.black,
    type: PieceType.pawn,
    position: 11,
    moved: false,
    moves: [],
  },
  {
    id: 13,
    player: Player.black,
    type: PieceType.pawn,
    position: 12,
    moved: false,
    moves: [],
  },
  {
    id: 14,
    player: Player.black,
    type: PieceType.pawn,
    position: 13,
    moved: false,
    moves: [],
  },
  {
    id: 15,
    player: Player.black,
    type: PieceType.pawn,
    position: 14,
    moved: false,
    moves: [],
  },
  {
    id: 16,
    player: Player.black,
    type: PieceType.pawn,
    position: 15,
    moved: false,
    moves: [],
  },
  {
    id: 17,
    player: Player.white,
    type: PieceType.pawn,
    position: 48,
    moved: false,
    moves: [],
  },
  {
    id: 18,
    player: Player.white,
    type: PieceType.pawn,
    position: 49,
    moved: false,
    moves: [],
  },
  {
    id: 19,
    player: Player.white,
    type: PieceType.pawn,
    position: 50,
    moved: false,
    moves: [],
  },
  {
    id: 20,
    player: Player.white,
    type: PieceType.pawn,
    position: 51,
    moved: false,
    moves: [],
  },
  {
    id: 21,
    player: Player.white,
    type: PieceType.pawn,
    position: 52,
    moved: false,
    moves: [],
  },
  {
    id: 22,
    player: Player.white,
    type: PieceType.pawn,
    position: 53,
    moved: false,
    moves: [],
  },
  {
    id: 23,
    player: Player.white,
    type: PieceType.pawn,
    position: 54,
    moved: false,
    moves: [],
  },
  {
    id: 24,
    player: Player.white,
    type: PieceType.pawn,
    position: 55,
    moved: false,
    moves: [],
  },
  {
    id: 25,
    player: Player.white,
    type: PieceType.rook,
    position: 56,
    moved: false,
    moves: [],
  },
  {
    id: 26,
    player: Player.white,
    type: PieceType.knight,
    position: 57,
    moved: false,
    moves: [],
  },
  {
    id: 27,
    player: Player.white,
    type: PieceType.bishop,
    position: 58,
    moved: false,
    moves: [],
  },
  {
    id: 28,
    player: Player.white,
    type: PieceType.queen,
    position: 59,
    moved: false,
    moves: [],
  },
  {
    id: 29,
    player: Player.white,
    type: PieceType.king,
    position: 60,
    moved: false,
    moves: [],
  },
  {
    id: 30,
    player: Player.white,
    type: PieceType.bishop,
    position: 61,
    moved: false,
    moves: [],
  },
  {
    id: 31,
    player: Player.white,
    type: PieceType.knight,
    position: 62,
    moved: false,
    moves: [],
  },
  {
    id: 32,
    player: Player.white,
    type: PieceType.rook,
    position: 63,
    moved: false,
    moves: [],
  },
];
