import { Piece, PieceType, Player } from '@/types/app.types';

export const initialPosition: Array<Piece> = [
  {
    id: 1,
    player: Player.black,
    type: PieceType.rook,
    position: 11,
    moved: false,
    moves: [],
  },
  {
    id: 2,
    player: Player.black,
    type: PieceType.knight,
    position: 12,
    moved: false,
    moves: [],
  },
  {
    id: 3,
    player: Player.black,
    type: PieceType.bishop,
    position: 13,
    moved: false,
    moves: [],
  },
  {
    id: 4,
    player: Player.black,
    type: PieceType.queen,
    position: 14,
    moved: false,
    moves: [],
  },
  {
    id: 5,
    player: Player.black,
    type: PieceType.king,
    position: 15,
    moved: false,
    moves: [],
  },
  {
    id: 6,
    player: Player.black,
    type: PieceType.bishop,
    position: 16,
    moved: false,
    moves: [],
  },
  {
    id: 7,
    player: Player.black,
    type: PieceType.knight,
    position: 17,
    moved: false,
    moves: [],
  },
  {
    id: 8,
    player: Player.black,
    type: PieceType.rook,
    position: 18,
    moved: false,
    moves: [],
  },
  {
    id: 9,
    player: Player.black,
    type: PieceType.pawn,
    position: 21,
    moved: false,
    moves: [],
  },
  {
    id: 10,
    player: Player.black,
    type: PieceType.pawn,
    position: 22,
    moved: false,
    moves: [],
  },
  {
    id: 11,
    player: Player.black,
    type: PieceType.pawn,
    position: 23,
    moved: false,
    moves: [],
  },
  {
    id: 12,
    player: Player.black,
    type: PieceType.pawn,
    position: 24,
    moved: false,
    moves: [],
  },
  {
    id: 13,
    player: Player.black,
    type: PieceType.pawn,
    position: 25,
    moved: false,
    moves: [],
  },
  {
    id: 14,
    player: Player.black,
    type: PieceType.pawn,
    position: 26,
    moved: false,
    moves: [],
  },
  {
    id: 15,
    player: Player.black,
    type: PieceType.pawn,
    position: 27,
    moved: false,
    moves: [],
  },
  {
    id: 16,
    player: Player.black,
    type: PieceType.pawn,
    position: 28,
    moved: false,
    moves: [],
  },
  {
    id: 17,
    player: Player.white,
    type: PieceType.pawn,
    position: 71,
    moved: false,
    moves: [],
  },
  {
    id: 18,
    player: Player.white,
    type: PieceType.pawn,
    position: 72,
    moved: false,
    moves: [],
  },
  {
    id: 19,
    player: Player.white,
    type: PieceType.pawn,
    position: 73,
    moved: false,
    moves: [],
  },
  {
    id: 20,
    player: Player.white,
    type: PieceType.pawn,
    position: 74,
    moved: false,
    moves: [],
  },
  {
    id: 21,
    player: Player.white,
    type: PieceType.pawn,
    position: 75,
    moved: false,
    moves: [],
  },
  {
    id: 22,
    player: Player.white,
    type: PieceType.pawn,
    position: 76,
    moved: false,
    moves: [],
  },
  {
    id: 23,
    player: Player.white,
    type: PieceType.pawn,
    position: 77,
    moved: false,
    moves: [],
  },
  {
    id: 24,
    player: Player.white,
    type: PieceType.pawn,
    position: 78,
    moved: false,
    moves: [],
  },
  {
    id: 25,
    player: Player.white,
    type: PieceType.rook,
    position: 81,
    moved: false,
    moves: [],
  },
  {
    id: 26,
    player: Player.white,
    type: PieceType.knight,
    position: 82,
    moved: false,
    moves: [],
  },
  {
    id: 27,
    player: Player.white,
    type: PieceType.bishop,
    position: 83,
    moved: false,
    moves: [],
  },
  {
    id: 28,
    player: Player.white,
    type: PieceType.queen,
    position: 84,
    moved: false,
    moves: [],
  },
  {
    id: 29,
    player: Player.white,
    type: PieceType.king,
    position: 85,
    moved: false,
    moves: [],
  },
  {
    id: 30,
    player: Player.white,
    type: PieceType.bishop,
    position: 86,
    moved: false,
    moves: [],
  },
  {
    id: 31,
    player: Player.white,
    type: PieceType.knight,
    position: 87,
    moved: false,
    moves: [],
  },
  {
    id: 32,
    player: Player.white,
    type: PieceType.rook,
    position: 88,
    moved: false,
    moves: [],
  },
];
