import { Piece, PieceType, Player } from '@/types/app.types';

export const initialPosition: Array<Piece> = [
  {
    id: 1,
    player: Player.black,
    type: PieceType.rook,
    position: 42,
    moved: false,
    moves: [],
  },
  {
    id: 2,
    player: Player.black,
    type: PieceType.knight,
    position: 12,
    moved: false,
    moves: [],
  },
  {
    id: 3,
    player: Player.white,
    type: PieceType.bishop,
    position: 86,
    moved: false,
    moves: [],
  },
  // {
  //   id: 4,
  //   player: Player.black,
  //   type: PieceType.queen,
  //   position: 14,
  //   moved: false,
  //   moves: [],
  // },
  {
    id: 5,
    player: Player.black,
    type: PieceType.king,
    position: 18,
    moved: false,
    moves: [],
  },
  // {
  //   id: 28,
  //   player: Player.white,
  //   type: PieceType.queen,
  //   position: 21,
  //   moved: false,
  //   moves: [],
  // },
  {
    id: 29,
    player: Player.white,
    type: PieceType.king,
    position: 37,
    moved: false,
    moves: [],
  },
  // {
  //   id: 30,
  //   player: Player.white,
  //   type: PieceType.bishop,
  //   position: 86,
  //   moved: false,
  //   moves: [],
  // },
  // {
  //   id: 31,
  //   player: Player.white,
  //   type: PieceType.knight,
  //   position: 87,
  //   moved: false,
  //   moves: [],
  // },
  // {
  //   id: 32,
  //   player: Player.white,
  //   type: PieceType.rook,
  //   position: 88,
  //   moved: false,
  //   moves: [],
  // },
];
